name = "pixi"
type = "package-manager"

[platform.linux]
archs = ["x86_64"]
exe-path = "pixi"
checksum-file = "pixi-x86_64-unknown-linux-musl.tar.gz.sha256"
download-file = "pixi-x86_64-unknown-linux-musl.tar.gz"

[platform.macos]
archs = ["x86_64"]
exe-path = "pixi"
checksum-file = "pixi-x86_64-apple-darwin.tar.gz.sha256"
download-file = "pixi-x86_64-apple-darwin.tar.gz"

[platform.windows]
archs = ["x86_64"]
exe-path = "pixi.exe"
checksum-file = "pixi-x86_64-pc-windows-msvc.zip.sha256"
download-file = "pixi-x86_64-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/prefix-dev/pixi/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/prefix-dev/pixi/releases/download/v{version}/{checksum_file}"

[install.exes.pixi]
primary = true

[resolve]
git-url = "https://github.com/prefix-dev/pixi"
version-pattern = "^v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"
